// auth routes
export const ROOT_ROUTE = '/'
export const HOME_ROUTE = '/home'
export const CREATE_ROUTE = '/create'
export const VIDEO_ROUTE = '/video/:id'
export const CHANNEL_FEATURED_ROUTE = '/channel/:id/featured'
export const CHANNEL_PLAYLISTS_ROUTE = '/channel/:id/playlists'
export const CHANNEL_CHANNELS_ROUTE = '/channel/:id/channels'
export const CHANNEL_ABOUT_ROUTE = '/channel/:id/about'
export const PLAYLIST_ROUTE = '/playlist/:id'
export const CREATE_PLAYLIST_ROUTE = '/create-playlist'
export const FIND_ROUTE = '/find/:title'
export const SETTINGS_ROUTE = '/settings'
// unauth routes
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'